name: Linux distros tests

on:
    pull_request:
        types: [labeled, synchronize]
    workflow_dispatch:
        inputs:
            test_type:
                type: choice
                description: Which series of tests to launch
                required: true
                options:
                - short
                - long
                - full

jobs:
    tests_long:
        name: Long (multi-distros, w/o cc)
        strategy:
            matrix:
                platform: [rockylinux10]
        runs-on: ubuntu-latest
        if: ${{ contains(github.event.pull_request.labels.*.name, 'tests:long') || inputs.test_type == 'long' }}
        timeout-minutes: 45
        steps:
        - uses: actions/checkout@v4
          with:
            persist-credentials: false
        - name: run tests inside a ${{ matrix.platform }} docker
          run: tests/functional/docker/docker_build_and_run_tests.sh ${{ matrix.platform }} --no-pause-on-fail
          env:
            DOCKER_TTY: false
