name: Basic tests

on: [push, pull_request]

jobs:
    test:
        name: perlcritic, perltidy & shellcheck
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v2
        - name: install prerequisites
          run: sudo apt update && sudo apt install -y shellcheck libperl-critic-perl perltidy
          env:
            DEBIAN_FRONTEND: noninteractive
        - name: shellcheck
          run: bin/dev/shell-check.sh
        - name: perl critic
          run: bin/dev/perl-critic.sh
        - name: perl tidy
          run: bin/dev/perl-tidy.sh test
